//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace CustomerMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }

		[Required(ErrorMessage = "Please input first name")]
		public string FirstName { get; set; }
		[Required(ErrorMessage = "Please input last name")]
		public string LastName { get; set; }
		[Required(ErrorMessage = "Please input age")]
		public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public Nullable<int> status { get; set; }
    }
}
