//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace ASPMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }

		[Required(ErrorMessage ="ป้อนชื่อก่อน")]
		[MinLength(5)]
		//[RegularExpression("^[A-Zก-ฮ]*$")]
		[RegularExpression("[ก-ฮ]")]
		[Display(Name ="ชื่อ")]
		public string FirstName { get; set; }

		[Required(ErrorMessage = "ป้อนนามสกุลก่อน")]
		public string LastName { get; set; }

		[Required(ErrorMessage = "ป้อนอายุก่อน")]
		public Nullable<int> Age { get; set; }
		[Required(ErrorMessage = "ป้อนชื่อก่อน")]
		public string Gender { get; set; }
		[Required(ErrorMessage = "ป้อนที่อยู่ก่อน")]
		public string Address { get; set; }
		[Required(ErrorMessage = "ป้อนสถานะก่อน")]
		public Nullable<int> status { get; set; }
    }
}
